### ISSUE TITLE
orthomclBlastParser error

### ISSUE THREAD

**Issue by anu24s** [stajichlab/OrthoMCL#10]
When I run orthomclBlastParser I get the error 
Illegal division by zero at orthomclBlastParser line 116.

Do you have any suggestion on how to solve this?
Thanks in advance.

**Comment by hyphaltip** [comment]
I would not use this code -use the formal releases from the OrthoMCL team
or use OrthoFinder2 as a more modern and appropriate tool.
---
Jason E Stajich, PhD
Professor, Dept of Microbiology and Plant Pathology
Chair, Academic Senate, Riverside Division
University of California, Riverside

Fellow, CIFAR Fungal Kingdom: Threats and Opportunities
<https://www.cifar.ca/research/program/fungal-kingdom>
email: jason.stajich@ucr.edu
twitter: @stajichlab <http://twitter.com/stajichlab> @hyphaltip
<http://twitter.com/hyphaltip> @zygolife <http://twitter.com/zygolife>
website: http://lab.stajich.org
office: +1 951.827.2363 mobile: +1 909.333.6709

**Comment by anu24s** [comment]
I am using customized version of [OrthoMCL](http://orthomcl.org/common/downloads/software/v2.0/) based on v2.0.9 and which is used within the [OrthoMCL Pipeline](https://github.com/apetkau/orthomcl-pipeline). 
My OrthoMCL Pipeline run got stopped in between, so from " Re-run orthoMCL-pipeline from a given stage ? #27 " , I started running orthomclBlastParser script using my blast results obtained.

I am clueless what to be done. where can I find formal releases from the OrthoMCL script?
Please help.

**Comment by hyphaltip** [comment]
please don't use this sqlite version and I would contact the main authors
and their site is here https://orthomcl.org/common/downloads/software/
https://orthomcl.org/orthomcl/
---
Jason E Stajich, PhD
Professor, Dept of Microbiology and Plant Pathology
Chair, Academic Senate, Riverside Division
University of California, Riverside

Fellow, CIFAR Fungal Kingdom: Threats and Opportunities
<https://www.cifar.ca/research/program/fungal-kingdom>
email: jason.stajich@ucr.edu
twitter: @stajichlab <http://twitter.com/stajichlab> @hyphaltip
<http://twitter.com/hyphaltip> @zygolife <http://twitter.com/zygolife>
website: http://lab.stajich.org
office: +1 951.827.2363 mobile: +1 909.333.6709

**Comment by anu24s** [comment]
Hi, I solved the error myself by concatenating all the  blast outputs into a single file. It worked fine after that.
